/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateJobArgs {
  'title' : string,
  'responsibilities' : Array<string>,
  'jobType' : JobType,
  'description' : string,
  'company' : string,
  'salaryRange' : string,
  'requirements' : Array<string>,
  'location' : string,
}
export interface Job {
  'id' : JobId,
  'title' : string,
  'responsibilities' : Array<string>,
  'jobType' : JobType,
  'postedDate' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'salaryRange' : string,
  'requirements' : Array<string>,
  'location' : string,
}
export interface JobFilters {
  'jobType' : [] | [JobType],
  'page' : bigint,
  'pageSize' : bigint,
  'searchQuery' : [] | [string],
  'location' : [] | [string],
}
export type JobId = bigint;
export type JobType = { 'Private' : null } |
  { 'Corporate' : null } |
  { 'Government' : null };
export interface JobsPage {
  'total' : bigint,
  'jobs' : Array<Job>,
  'page' : bigint,
  'pageSize' : bigint,
}
export type Timestamp = bigint;
export interface UpdateJobArgs {
  'id' : JobId,
  'title' : string,
  'responsibilities' : Array<string>,
  'jobType' : JobType,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'salaryRange' : string,
  'requirements' : Array<string>,
  'location' : string,
}
export interface _SERVICE {
  'createJob' : ActorMethod<[CreateJobArgs], Job>,
  'deleteJob' : ActorMethod<[JobId], boolean>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getJobById' : ActorMethod<[JobId], [] | [Job]>,
  'getJobs' : ActorMethod<[JobFilters], JobsPage>,
  'isAdmin' : ActorMethod<[], boolean>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'updateJob' : ActorMethod<[UpdateJobArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];