/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobType = IDL.Variant({
  'Private' : IDL.Null,
  'Corporate' : IDL.Null,
  'Government' : IDL.Null,
});
export const CreateJobArgs = IDL.Record({
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'jobType' : JobType,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const JobId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'jobType' : JobType,
  'postedDate' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const JobFilters = IDL.Record({
  'jobType' : IDL.Opt(JobType),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'searchQuery' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const JobsPage = IDL.Record({
  'total' : IDL.Nat,
  'jobs' : IDL.Vec(Job),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const UpdateJobArgs = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'jobType' : JobType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'createJob' : IDL.Func([CreateJobArgs], [Job], []),
  'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getJobById' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getJobs' : IDL.Func([JobFilters], [JobsPage], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'updateJob' : IDL.Func([UpdateJobArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobType = IDL.Variant({
    'Private' : IDL.Null,
    'Corporate' : IDL.Null,
    'Government' : IDL.Null,
  });
  const CreateJobArgs = IDL.Record({
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'jobType' : JobType,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const JobId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'jobType' : JobType,
    'postedDate' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const JobFilters = IDL.Record({
    'jobType' : IDL.Opt(JobType),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'searchQuery' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const JobsPage = IDL.Record({
    'total' : IDL.Nat,
    'jobs' : IDL.Vec(Job),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const UpdateJobArgs = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'jobType' : JobType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'createJob' : IDL.Func([CreateJobArgs], [Job], []),
    'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getJobById' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getJobs' : IDL.Func([JobFilters], [JobsPage], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'updateJob' : IDL.Func([UpdateJobArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };