/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface JobsPage {
    total: bigint;
    jobs: Array<Job>;
    page: bigint;
    pageSize: bigint;
}
export type Timestamp = bigint;
export interface Job {
    id: JobId;
    title: string;
    responsibilities: Array<string>;
    jobType: JobType;
    postedDate: Timestamp;
    description: string;
    isActive: boolean;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
}
export interface CreateJobArgs {
    title: string;
    responsibilities: Array<string>;
    jobType: JobType;
    description: string;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
}
export type JobId = bigint;
export interface UpdateJobArgs {
    id: JobId;
    title: string;
    responsibilities: Array<string>;
    jobType: JobType;
    description: string;
    isActive: boolean;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
}
export interface JobFilters {
    jobType?: JobType;
    page: bigint;
    pageSize: bigint;
    searchQuery?: string;
    location?: string;
}
export enum JobType {
    Private = "Private",
    Corporate = "Corporate",
    Government = "Government"
}
export interface backendInterface {
    createJob(args: CreateJobArgs): Promise<Job>;
    deleteJob(id: JobId): Promise<boolean>;
    getAdminPrincipal(): Promise<Principal | null>;
    getJobById(id: JobId): Promise<Job | null>;
    getJobs(filters: JobFilters): Promise<JobsPage>;
    isAdmin(): Promise<boolean>;
    setAdmin(newAdmin: Principal): Promise<void>;
    updateJob(args: UpdateJobArgs): Promise<boolean>;
}
import type { CreateJobArgs as _CreateJobArgs, Job as _Job, JobFilters as _JobFilters, JobId as _JobId, JobType as _JobType, JobsPage as _JobsPage, Timestamp as _Timestamp, UpdateJobArgs as _UpdateJobArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createJob(arg0: CreateJobArgs): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_CreateJobArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Job_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_CreateJobArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Job_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobById(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobs(arg0: JobFilters): Promise<JobsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobs(to_candid_JobFilters_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JobsPage_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobs(to_candid_JobFilters_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JobsPage_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async setAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async updateJob(arg0: UpdateJobArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_UpdateJobArgs_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_UpdateJobArgs_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_JobType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_JobsPage_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobsPage): JobsPage {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    jobs: Array<_Job>;
    page: bigint;
    pageSize: bigint;
}): {
    total: bigint;
    jobs: Array<Job>;
    page: bigint;
    pageSize: bigint;
} {
    return {
        total: value.total,
        jobs: from_candid_vec_n15(_uploadFile, _downloadFile, value.jobs),
        page: value.page,
        pageSize: value.pageSize
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    title: string;
    responsibilities: Array<string>;
    jobType: _JobType;
    postedDate: _Timestamp;
    description: string;
    isActive: boolean;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
}): {
    id: JobId;
    title: string;
    responsibilities: Array<string>;
    jobType: JobType;
    postedDate: Timestamp;
    description: string;
    isActive: boolean;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        responsibilities: value.responsibilities,
        jobType: from_candid_JobType_n7(_uploadFile, _downloadFile, value.jobType),
        postedDate: value.postedDate,
        description: value.description,
        isActive: value.isActive,
        company: value.company,
        salaryRange: value.salaryRange,
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Private: null;
} | {
    Corporate: null;
} | {
    Government: null;
}): JobType {
    return "Private" in value ? JobType.Private : "Corporate" in value ? JobType.Corporate : "Government" in value ? JobType.Government : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateJobArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobArgs): _CreateJobArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JobFilters_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobFilters): _JobFilters {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobArgs_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobArgs): _UpdateJobArgs {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobType?: JobType;
    page: bigint;
    pageSize: bigint;
    searchQuery?: string;
    location?: string;
}): {
    jobType: [] | [_JobType];
    page: bigint;
    pageSize: bigint;
    searchQuery: [] | [string];
    location: [] | [string];
} {
    return {
        jobType: value.jobType ? candid_some(to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType)) : candid_none(),
        page: value.page,
        pageSize: value.pageSize,
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobId;
    title: string;
    responsibilities: Array<string>;
    jobType: JobType;
    description: string;
    isActive: boolean;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
}): {
    id: _JobId;
    title: string;
    responsibilities: Array<string>;
    jobType: _JobType;
    description: string;
    isActive: boolean;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        responsibilities: value.responsibilities,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        isActive: value.isActive,
        company: value.company,
        salaryRange: value.salaryRange,
        requirements: value.requirements,
        location: value.location
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    responsibilities: Array<string>;
    jobType: JobType;
    description: string;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
}): {
    title: string;
    responsibilities: Array<string>;
    jobType: _JobType;
    description: string;
    company: string;
    salaryRange: string;
    requirements: Array<string>;
    location: string;
} {
    return {
        title: value.title,
        responsibilities: value.responsibilities,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        company: value.company,
        salaryRange: value.salaryRange,
        requirements: value.requirements,
        location: value.location
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    Private: null;
} | {
    Corporate: null;
} | {
    Government: null;
} {
    return value == JobType.Private ? {
        Private: null
    } : value == JobType.Corporate ? {
        Corporate: null
    } : value == JobType.Government ? {
        Government: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
